import { useMemo, useState } from 'react';
import type { StaffAssignmentRecord, Veteran } from '../../types/domain';
import { StaffAssignmentForm } from './StaffAssignmentForm';

interface Props { veterans: Veteran[]; assignments: StaffAssignmentRecord[]; onSave:(record:StaffAssignmentRecord)=>void; onRemove:(id:string)=>void; }
export function StaffAssignmentsPage({ veterans, assignments, onSave, onRemove }:Props){
  const today=new Date().toISOString().slice(0,10); const [editing,setEditing]=useState<StaffAssignmentRecord|undefined>(); const [showForm,setShowForm]=useState(false); const [date,setDate]=useState(today); const [shift,setShift]=useState('All');
  const rows=useMemo(()=>assignments.filter(a=>a.assignmentDate===date&&(shift==='All'||a.shift===shift)).sort((a,b)=>a.startTime.localeCompare(b.startTime)),[assignments,date,shift]);
  const activeVeterans=veterans.filter(v=>v.status!=='Discharged / Archived'); const covered=new Set(rows.filter(a=>a.status!=='Called Off').flatMap(a=>a.veteranIds)); const uncovered=activeVeterans.filter(v=>!covered.has(v.id));
  const charge=rows.find(a=>a.isChargeNurse&&a.status!=='Called Off'); const calledOff=rows.filter(a=>a.status==='Called Off').length; const present=rows.filter(a=>a.status==='Present').length;
  if(showForm) return <StaffAssignmentForm veterans={veterans} initial={editing} onCancel={()=>{setEditing(undefined);setShowForm(false)}} onSave={r=>{onSave(r);setEditing(undefined);setShowForm(false)}} />;
  return <section>
    <div className="page-heading"><div><p className="eyebrow">Module 5</p><h2>Staff Assignments &amp; Shift Coverage</h2><p>Coordinate licensed and non-licensed coverage, Veteran workloads, and handoff responsibility.</p></div><button className="primary" onClick={()=>setShowForm(true)}>Add assignment</button></div>
    <div className="metric-grid staff-metrics"><article><span>Scheduled</span><strong>{rows.length}</strong></article><article><span>Present</span><strong>{present}</strong></article><article><span>Charge coverage</span><strong className={charge?'good':'danger'}>{charge?'Covered':'Gap'}</strong></article><article><span>Uncovered Veterans</span><strong className={uncovered.length?'danger':'good'}>{uncovered.length}</strong></article><article><span>Called off</span><strong>{calledOff}</strong></article></div>
    {(uncovered.length>0||!charge)&&<div className="coverage-alert"><b>Coverage action required:</b> {!charge&&'No charge nurse is assigned. '}{uncovered.length>0&&`${uncovered.length} active Veteran${uncovered.length===1?' is':'s are'} not assigned.`}</div>}
    <div className="panel filter-row"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} /></label><label>Shift<select value={shift} onChange={e=>setShift(e.target.value)}><option>All</option><option>Day</option><option>Evening</option><option>Night</option></select></label></div>
    <div className="panel table-wrap"><table><thead><tr><th>Staff</th><th>Role</th><th>Shift</th><th>Hours</th><th>Status</th><th>Zone</th><th>Veterans</th><th>Treatment scope</th><th>Actions</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={9} className="empty-cell">No assignments for this date and shift.</td></tr>:rows.map(a=><tr key={a.id} className={a.status==='Called Off'?'row-alert':''}><td><b>{a.staffName}</b>{a.isChargeNurse&&<span className="mini-badge">Charge</span>}</td><td>{a.role}</td><td>{a.shift}</td><td>{a.startTime}–{a.endTime}</td><td><span className={`status-pill ${a.status.toLowerCase().replaceAll(' ','-')}`}>{a.status}</span></td><td>{a.zone||'—'}</td><td>{a.veteranIds.length}</td><td>{a.treatmentCategories.join(', ')||'—'}</td><td><div className="table-actions"><button className="link-button" onClick={()=>{setEditing(a);setShowForm(true)}}>Edit</button><button className="link-button danger-text" onClick={()=>confirm('Remove this assignment?')&&onRemove(a.id)}>Remove</button></div></td></tr>)}</tbody></table></div>
    <div className="two-column"><div className="panel"><h3>Uncovered Veterans</h3>{uncovered.length===0?<p className="good-text">All active Veterans have assigned staff coverage.</p>:<ul className="coverage-list">{uncovered.map(v=><li key={v.id}><b>Room {v.room}</b><span>{v.name}</span></li>)}</ul>}</div><div className="panel"><h3>Shift Handoff</h3>{rows.filter(a=>a.notes).length===0?<p className="muted">No staff handoff notes recorded.</p>:<ul className="handoff-list">{rows.filter(a=>a.notes).map(a=><li key={a.id}><b>{a.staffName}</b><span>{a.notes}</span></li>)}</ul>}</div></div>
  </section>;
}
