import { useEffect, useState } from 'react';
import { AppShell, type AppPage } from './components/AppShell';
import { AppointmentsPage } from './features/appointments/AppointmentsPage';
import { CalendarPage } from './features/appointments/CalendarPage';
import { Dashboard } from './features/dashboard/Dashboard';
import { TransportPage } from './features/transport/TransportPage';
import { StaffAssignmentsPage } from './features/staff/StaffAssignmentsPage';
import { VeteranMasterRecord } from './features/veterans/VeteranMasterRecord';
import { MorningReportPage } from './features/morning-report/MorningReportPage';
import { TreatmentsPage } from './features/treatments/TreatmentsPage';
import { ManagedListsPage } from './features/managed-lists/ManagedListsPage';
import { loadState, saveState } from './lib/storage';
import type { Appointment, BravoShiftState, ManagedLists, MorningReportNote, StaffAssignmentRecord, Treatment, TreatmentCompletion, TravelRequest, Veteran } from './types/domain';
export default function App(){const[state,setState]=useState<BravoShiftState>(()=>loadState());const[activePage,setActivePage]=useState<AppPage>('dashboard');const[calendarEdit,setCalendarEdit]=useState<Appointment|undefined>();useEffect(()=>saveState(state),[state]);
const upsert=<T extends{id:string}>(key:keyof BravoShiftState,item:T)=>setState(c=>({...c,[key]:(c[key] as unknown as T[]).some(x=>x.id===item.id)?(c[key] as unknown as T[]).map(x=>x.id===item.id?item:x):[...(c[key] as unknown as T[]),item]}));
function upsertVeteran(v:Veteran){upsert('veterans',v)} function archiveVeteran(id:string){const n=new Date().toISOString();setState(c=>({...c,veterans:c.veterans.map(v=>v.id===id?{...v,status:'Discharged / Archived',archivedAt:n,updatedAt:n}:v)}))} function restoreVeteran(id:string){const n=new Date().toISOString();setState(c=>({...c,veterans:c.veterans.map(v=>v.id===id?{...v,status:'Active',archivedAt:undefined,updatedAt:n}:v)}))}
function upsertAppointment(a:Appointment){upsert('appointments',a);setCalendarEdit(undefined)} function upsertTreatment(t:Treatment){upsert('treatments',t)} function archiveTreatment(id:string){const n=new Date().toISOString();setState(c=>({...c,treatments:c.treatments.map(t=>t.id===id?{...t,active:false,archivedAt:n,updatedAt:n}:t)}))} function restoreTreatment(id:string){const n=new Date().toISOString();setState(c=>({...c,treatments:c.treatments.map(t=>t.id===id?{...t,active:true,archivedAt:undefined,updatedAt:n}:t)}))}
function toggleTreatmentComplete(t:Treatment,date:string,shift:'Day'|'Night',completedBy:string){setState(c=>{const e=c.treatmentCompletions.find(x=>x.treatmentId===t.id&&x.completionDate===date&&x.shift===shift);if(e)return{...c,treatmentCompletions:c.treatmentCompletions.filter(x=>x.id!==e.id)};const n:TreatmentCompletion={id:crypto.randomUUID(),treatmentId:t.id,completionDate:date,shift,completedAt:new Date().toISOString(),completedBy:completedBy.trim()};return{...c,treatmentCompletions:[...c.treatmentCompletions,n]}})}
function upsertTravelRequest(r:TravelRequest){upsert('travelRequests',r)} function upsertStaffAssignment(r:StaffAssignmentRecord){upsert('staffAssignmentRecords',r)} function removeStaffAssignment(id:string){setState(c=>({...c,staffAssignmentRecords:c.staffAssignmentRecords.filter(x=>x.id!==id)}))} function upsertMorningNote(n:MorningReportNote){upsert('morningReportNotes',n)} function removeMorningNote(id:string){setState(c=>({...c,morningReportNotes:c.morningReportNotes.filter(x=>x.id!==id)}))} function setLists(l:ManagedLists){setState(c=>({...c,managedLists:l}))}
let content;if(activePage==='dashboard')content=<Dashboard state={state} onAddVeteran={()=>setActivePage('veterans')}/>;else if(activePage==='veterans')content=<VeteranMasterRecord veterans={state.veterans} onSave={upsertVeteran} onArchive={archiveVeteran} onRestore={restoreVeteran} lists={state.managedLists}/>;else if(activePage==='appointments')content=<AppointmentsPage veterans={state.veterans} appointments={state.appointments} onSave={upsertAppointment} initialEdit={calendarEdit} lists={state.managedLists}/>;else if(activePage==='calendar')content=<CalendarPage veterans={state.veterans} appointments={state.appointments} onEdit={a=>{setCalendarEdit(a);setActivePage('appointments')}}/>;else if(activePage==='transport')content=<TransportPage veterans={state.veterans} appointments={state.appointments} travelRequests={state.travelRequests} onSave={upsertTravelRequest} lists={state.managedLists}/>;else if(activePage==='treatments')content=<TreatmentsPage veterans={state.veterans} treatments={state.treatments} completions={state.treatmentCompletions} onSave={upsertTreatment} onArchive={archiveTreatment} onRestore={restoreTreatment} onToggleComplete={toggleTreatmentComplete} lists={state.managedLists}/>;else if(activePage==='staff')content=<StaffAssignmentsPage veterans={state.veterans} assignments={state.staffAssignmentRecords} onSave={upsertStaffAssignment} onRemove={removeStaffAssignment}/>;else if(activePage==='morning-report')content=<MorningReportPage state={state} notes={state.morningReportNotes} onSaveNote={upsertMorningNote} onRemoveNote={removeMorningNote}/>;else content=<ManagedListsPage lists={state.managedLists} onChange={setLists}/>;return <AppShell activePage={activePage} onNavigate={p=>{setCalendarEdit(undefined);setActivePage(p)}}>{content}</AppShell>}
