import { useMemo, useState } from 'react';
import type { CommunicationCategory, CommunicationPriority, NotificationRecord, NotificationStatus, ShiftBroadcast, StaffMessage, TaskReminder, Veteran } from '../../types/domain';

type Tab = 'notifications' | 'messages' | 'broadcasts' | 'reminders';
interface Props {
  veterans: Veteran[];
  notifications: NotificationRecord[];
  messages: StaffMessage[];
  broadcasts: ShiftBroadcast[];
  reminders: TaskReminder[];
  onSaveNotification: (item: NotificationRecord) => void;
  onSaveMessage: (item: StaffMessage) => void;
  onSaveBroadcast: (item: ShiftBroadcast) => void;
  onSaveReminder: (item: TaskReminder) => void;
}
const priorities: CommunicationPriority[] = ['Routine','Important','Urgent','STAT'];
const categories: CommunicationCategory[] = ['Clinical','Transportation','Staffing','Administrative'];
const nowLocal = () => new Date().toISOString().slice(0,16);
const veteranName = (veterans: Veteran[], id?: string) => veterans.find(v => v.id === id)?.name ?? 'General / Unit';

export function CommunicationHubPage(props: Props) {
  const [tab,setTab]=useState<Tab>('notifications');
  const [filter,setFilter]=useState<'All'|'Unread'|CommunicationCategory>('All');
  const activeNotifications=useMemo(()=>props.notifications.filter(n=>filter==='All'||(filter==='Unread'?n.status==='Unread':n.category===filter)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),[props.notifications,filter]);
  const critical=props.notifications.filter(n=>n.priority==='STAT'&&n.status!=='Completed').length;
  const unread=props.notifications.filter(n=>n.status==='Unread').length;
  const escalated=props.notifications.filter(n=>n.status==='Escalated').length;
  const due=props.reminders.filter(r=>!r.completed&&r.dueAt&&new Date(r.dueAt)<=new Date()).length;

  function updateNotification(item: NotificationRecord, status: NotificationStatus) {
    props.onSaveNotification({...item,status,escalationLevel:status==='Escalated'?item.escalationLevel+1:item.escalationLevel,updatedAt:new Date().toISOString()});
  }
  return <section className="feature-page communication-hub">
    <div className="page-heading"><div><p className="eyebrow">BravoShift 2.9</p><h2>Notifications & Communication Hub</h2><p>Coordinate clinical work, staffing, transportation, and shift communications from one queue.</p></div><button className="secondary-button no-print" onClick={()=>window.print()}>Print Communication Report</button></div>
    <div className="metric-grid communication-metrics"><article className="metric-card"><span>Unread alerts</span><strong>{unread}</strong></article><article className="metric-card"><span>STAT active</span><strong>{critical}</strong></article><article className="metric-card"><span>Escalated</span><strong>{escalated}</strong></article><article className="metric-card"><span>Tasks overdue</span><strong>{due}</strong></article></div>
    <div className="communication-tabs no-print">{(['notifications','messages','broadcasts','reminders'] as Tab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>
    {tab==='notifications' && <>
      <NotificationComposer veterans={props.veterans} onSave={props.onSaveNotification}/>
      <div className="filter-row no-print"><label>Filter<select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option>All</option><option>Unread</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label></div>
      <div className="communication-list">{activeNotifications.length===0?<div className="panel"><p>No alerts match this filter.</p></div>:activeNotifications.map(n=><article key={n.id} className={`communication-card priority-${n.priority.toLowerCase()}`}><div className="communication-card-head"><div><span className="status-badge">{n.category}</span> <span className="status-badge">{n.priority}</span><h3>{n.title}</h3></div><strong>{n.status}</strong></div><p>{n.details}</p><small>{veteranName(props.veterans,n.veteranId)} · Assigned: {n.assignedTo||'Unassigned'} · Source: {n.source} · {new Date(n.createdAt).toLocaleString()}</small><div className="action-row no-print"><button onClick={()=>updateNotification(n,'Read')}>Read</button><button onClick={()=>updateNotification(n,'Acknowledged')}>Acknowledge</button><button onClick={()=>updateNotification(n,'Completed')}>Complete</button><button className="danger-button" onClick={()=>updateNotification(n,'Escalated')}>Escalate</button></div></article>)}</div>
    </>}
    {tab==='messages' && <><MessageComposer veterans={props.veterans} onSave={props.onSaveMessage}/><div className="communication-list">{props.messages.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(m=><article className={`communication-card priority-${m.priority.toLowerCase()}`} key={m.id}><div className="communication-card-head"><div><span className="status-badge">{m.priority}</span><h3>{m.subject}</h3></div><strong>{m.read?'Read':'Unread'}</strong></div><p>{m.body}</p><small>From {m.from} to {m.to} · {veteranName(props.veterans,m.veteranId)} · {new Date(m.createdAt).toLocaleString()}</small>{!m.read&&<div className="action-row no-print"><button onClick={()=>props.onSaveMessage({...m,read:true})}>Mark read</button></div>}</article>)}</div></>}
    {tab==='broadcasts' && <><BroadcastComposer onSave={props.onSaveBroadcast}/><div className="communication-list">{props.broadcasts.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(b=><article className={`communication-card priority-${b.priority.toLowerCase()}`} key={b.id}><div className="communication-card-head"><div><span className="status-badge">{b.shift} shift</span><h3>{b.title}</h3></div><strong>{b.active?'Active':'Closed'}</strong></div><p>{b.message}</p><small>Posted {new Date(b.createdAt).toLocaleString()}</small>{b.active&&<div className="action-row no-print"><button onClick={()=>props.onSaveBroadcast({...b,active:false})}>Close broadcast</button></div>}</article>)}</div></>}
    {tab==='reminders' && <><ReminderComposer veterans={props.veterans} onSave={props.onSaveReminder}/><div className="communication-list">{props.reminders.slice().sort((a,b)=>a.dueAt.localeCompare(b.dueAt)).map(r=><article className={`communication-card ${!r.completed&&r.dueAt&&new Date(r.dueAt)<=new Date()?'priority-urgent':''}`} key={r.id}><div className="communication-card-head"><div><span className="status-badge">{r.category}</span><h3>{r.title}</h3></div><strong>{r.completed?'Completed':'Open'}</strong></div><small>{veteranName(props.veterans,r.veteranId)} · Assigned: {r.assignedTo} · Due {r.dueAt?new Date(r.dueAt).toLocaleString():'Not set'}</small>{!r.completed&&<div className="action-row no-print"><button onClick={()=>props.onSaveReminder({...r,completed:true})}>Complete task</button></div>}</article>)}</div></>}
  </section>
}

function NotificationComposer({veterans,onSave}:{veterans:Veteran[];onSave:(x:NotificationRecord)=>void}){
 const [title,setTitle]=useState(''); const [details,setDetails]=useState(''); const [category,setCategory]=useState<CommunicationCategory>('Clinical'); const [priority,setPriority]=useState<CommunicationPriority>('Routine'); const [veteranId,setVeteranId]=useState(''); const [assignedTo,setAssignedTo]=useState('');
 return <form className="panel communication-composer no-print" onSubmit={e=>{e.preventDefault();if(!title.trim())return;const now=new Date().toISOString();onSave({id:crypto.randomUUID(),title:title.trim(),details:details.trim(),category,priority,status:'Unread',veteranId:veteranId||undefined,assignedTo,source:'Manual',escalationLevel:0,createdAt:now,updatedAt:now});setTitle('');setDetails('')}}><h3>Create alert</h3><div className="form-grid"><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Veteran<select value={veteranId} onChange={e=>setVeteranId(e.target.value)}><option value="">General / Unit</option>{veterans.filter(v=>!v.archivedAt).map(v=><option value={v.id} key={v.id}>{v.room} — {v.name}</option>)}</select></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value as CommunicationCategory)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value as CommunicationPriority)}>{priorities.map(x=><option key={x}>{x}</option>)}</select></label><label>Assigned to<input value={assignedTo} onChange={e=>setAssignedTo(e.target.value)} placeholder="Charge Nurse, RN, Transport..."/></label><label className="span-2">Details<textarea value={details} onChange={e=>setDetails(e.target.value)}/></label></div><button className="primary-button">Create alert</button></form>
}
function MessageComposer({veterans,onSave}:{veterans:Veteran[];onSave:(x:StaffMessage)=>void}){const [from,setFrom]=useState('Charge Nurse');const [to,setTo]=useState('');const [subject,setSubject]=useState('');const [body,setBody]=useState('');const [priority,setPriority]=useState<CommunicationPriority>('Routine');const [veteranId,setVeteranId]=useState('');return <form className="panel communication-composer no-print" onSubmit={e=>{e.preventDefault();if(!to||!subject)return;onSave({id:crypto.randomUUID(),from,to,subject,body,priority,veteranId:veteranId||undefined,read:false,createdAt:new Date().toISOString()});setSubject('');setBody('')}}><h3>Send internal message</h3><div className="form-grid"><label>From<input value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input value={to} onChange={e=>setTo(e.target.value)} required/></label><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} required/></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value as CommunicationPriority)}>{priorities.map(x=><option key={x}>{x}</option>)}</select></label><label>Veteran<select value={veteranId} onChange={e=>setVeteranId(e.target.value)}><option value="">General / Unit</option>{veterans.map(v=><option key={v.id} value={v.id}>{v.room} — {v.name}</option>)}</select></label><label className="span-2">Message<textarea value={body} onChange={e=>setBody(e.target.value)}/></label></div><button className="primary-button">Send message</button></form>}
function BroadcastComposer({onSave}:{onSave:(x:ShiftBroadcast)=>void}){const [title,setTitle]=useState('');const [message,setMessage]=useState('');const [shift,setShift]=useState<ShiftBroadcast['shift']>('All');const [priority,setPriority]=useState<CommunicationPriority>('Routine');return <form className="panel communication-composer no-print" onSubmit={e=>{e.preventDefault();if(!title)return;onSave({id:crypto.randomUUID(),title,message,shift,priority,active:true,createdAt:new Date().toISOString()});setTitle('');setMessage('')}}><h3>Post shift broadcast</h3><div className="form-grid"><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Shift<select value={shift} onChange={e=>setShift(e.target.value as ShiftBroadcast['shift'])}><option>All</option><option>Day</option><option>Evening</option><option>Night</option></select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value as CommunicationPriority)}>{priorities.map(x=><option key={x}>{x}</option>)}</select></label><label className="span-2">Announcement<textarea value={message} onChange={e=>setMessage(e.target.value)}/></label></div><button className="primary-button">Post broadcast</button></form>}
function ReminderComposer({veterans,onSave}:{veterans:Veteran[];onSave:(x:TaskReminder)=>void}){const [title,setTitle]=useState('');const [assignedTo,setAssignedTo]=useState('');const [dueAt,setDueAt]=useState(nowLocal());const [veteranId,setVeteranId]=useState('');const [category,setCategory]=useState<CommunicationCategory>('Clinical');return <form className="panel communication-composer no-print" onSubmit={e=>{e.preventDefault();if(!title)return;onSave({id:crypto.randomUUID(),title,assignedTo,dueAt,veteranId:veteranId||undefined,category,completed:false,createdAt:new Date().toISOString()});setTitle('')}}><h3>Create task reminder</h3><div className="form-grid"><label>Task<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Assigned to<input value={assignedTo} onChange={e=>setAssignedTo(e.target.value)}/></label><label>Due<input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value as CommunicationCategory)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Veteran<select value={veteranId} onChange={e=>setVeteranId(e.target.value)}><option value="">General / Unit</option>{veterans.map(v=><option key={v.id} value={v.id}>{v.room} — {v.name}</option>)}</select></label></div><button className="primary-button">Create reminder</button></form>}
