import { useMemo, useState } from 'react';
import type { Appointment, TravelRequest, Veteran, ManagedLists } from '../../types/domain';
import { TicketToRide } from './TicketToRide';
import { TransportForm } from './TransportForm';

export function TransportPage({veterans,appointments,travelRequests,onSave,lists}:{veterans:Veteran[];appointments:Appointment[];travelRequests:TravelRequest[];onSave:(r:TravelRequest)=>void;lists:ManagedLists}){
 const [editing,setEditing]=useState<TravelRequest|undefined>(); const [showForm,setShowForm]=useState(false); const [ticket,setTicket]=useState<TravelRequest|undefined>(); const [query,setQuery]=useState(''); const [status,setStatus]=useState('');
 const veteranMap=useMemo(()=>new Map(veterans.map(v=>[v.id,v])),[veterans]); const appointmentMap=useMemo(()=>new Map(appointments.map(a=>[a.id,a])),[appointments]);
 const filtered=travelRequests.filter(r=>{const v=veteranMap.get(r.veteranId); const hay=`${v?.name||''} ${v?.room||''} ${r.driver} ${r.transportMode}`.toLowerCase(); return (!query||hay.includes(query.toLowerCase()))&&(!status||r.status===status)}).sort((a,b)=>(a.pickupTime||'9999').localeCompare(b.pickupTime||'9999'));
 const counts={pending:travelRequests.filter(r=>['Draft','Pending'].includes(r.status)).length,confirmed:travelRequests.filter(r=>r.status==='Confirmed').length,offUnit:travelRequests.filter(r=>['En Route','At Destination','Awaiting Return'].includes(r.status)).length,returning:travelRequests.filter(r=>r.status==='Awaiting Return').length,failed:travelRequests.filter(r=>r.status==='Failed').length};
 function save(r:TravelRequest){onSave(r);setEditing(undefined);setShowForm(false)}
 if(ticket) return <TicketToRide request={ticket} veteran={veteranMap.get(ticket.veteranId)} appointment={appointmentMap.get(ticket.appointmentId)} onClose={()=>setTicket(undefined)}/>;
 return <section>
  <div className="section-heading"><div><p className="eyebrow">Operational movement control</p><h2>Transportation & Ticket to Ride</h2><p>Coordinate requests, off-unit status, returns, and printable clinical handoffs.</p></div><button className="primary" onClick={()=>{setEditing(undefined);setShowForm(true)}}>New Travel Request</button></div>
  <div className="metric-grid transport-metrics"><article><span>Pending</span><strong>{counts.pending}</strong></article><article><span>Confirmed</span><strong>{counts.confirmed}</strong></article><article><span>Off Unit</span><strong>{counts.offUnit}</strong></article><article><span>Awaiting Return</span><strong>{counts.returning}</strong></article><article><span>Failed</span><strong>{counts.failed}</strong></article></div>
  {(showForm||editing)&&<TransportForm veterans={veterans} appointments={appointments} initial={editing} onSave={save} onCancel={()=>{setShowForm(false);setEditing(undefined)}} lists={lists}/>}
  <div className="panel"><div className="toolbar"><input aria-label="Search transportation" placeholder="Search Veteran, room, driver, mode..." value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['Draft','Pending','Confirmed','En Route','At Destination','Awaiting Return','Completed','Failed','Cancelled'].map(s=><option key={s}>{s}</option>)}</select></div>
   <div className="table-wrap"><table><thead><tr><th>Veteran</th><th>Appointment</th><th>Pickup</th><th>Mode</th><th>Driver / Escort</th><th>Status</th><th>Return</th><th>Actions</th></tr></thead><tbody>{filtered.length?filtered.map(r=>{const v=veteranMap.get(r.veteranId),a=appointmentMap.get(r.appointmentId);return <tr key={r.id}><td><b>{v?.name||'Unknown'}</b><br/><span className="muted">Room {v?.room||'—'}</span></td><td>{a?`${a.date} ${a.time}`:'Unlinked'}<br/><span className="muted">{a?.destination||''}</span></td><td>{r.pickupTime||'—'}</td><td>{r.transportMode}<br/><span className="muted">{r.mobilityMode}</span></td><td>{r.driver||'Unassigned'}<br/><span className="muted">{r.escortRequired?`Escort: ${r.escortName||'Required'}`:'No escort'}</span></td><td><span className={`status-pill ${r.status.toLowerCase().replaceAll(' ','-')}`}>{r.status}</span></td><td>{r.estimatedReturn||'—'}</td><td><button className="link-button" onClick={()=>{setEditing(r);setShowForm(false)}}>Edit</button> <button className="link-button" onClick={()=>setTicket(r)}>Ticket</button></td></tr>}):<tr><td colSpan={8} className="empty-state">No travel requests match the current filters.</td></tr>}</tbody></table></div>
  </div>
 </section>
}
